In [64]:
import numpy as np
# 创建一个单位矩阵（主对角线元素为1，其余为0的正方形矩阵）
i2 = np.eye(2)
i2

array([[ 1.,  0.],
       [ 0.,  1.]])

In [3]:
np.savetxt("eye.txt",i2)     # savetxt函数将数据存储到文件中

In [4]:
# data.csv 
#股票代码    日期    空    开盘价   最高价   最低价   收盘价   成交量
#AAPL	28-01-2011		344.17	344.4	333.53	336.1	21144800
#AAPL	29-01-2012		340.31	345.5	332.3	335.1	22312220
#AAPL	30-01-2013		332.12	339.01	330.23	336.34	23456190
#AAPL	31-01-2014		338.32	348.03	340.23	345.02	23435550
#AAPL	28-01-2015		346.1	350.24	348.12	349.38	30021113
#AAPL	28-01-2016		350.12	352.66	349.2	352.12	21214400

In [5]:
import numpy as np
# usecols 的参数为一个元组
c,v = np.loadtxt('/Users/fountain/Desktop/data.csv',delimiter=',', usecols=(6,7), unpack=True)
# 加权平均值是由每个分量乘以反映其重要性的因子得到的平均值。
#考虑数组[1,2,3,4]和相应的权重[4,3,2,1]，通过将相应元素的乘积相加，并将和除以权重的和，来计算加权平均值。
vwap = np.average(c,weights=v)   #  计算成交量加权平均价格
print "VWAP=",vwap

VWAP= 342.674864711


In [6]:
t = np.arange(len(c))
twap = np.average(c,weights=t)
print "TWAP=",twap    #计算时间加权平均价格

TWAP= 346.730666667


In [7]:
# 算数平均值
print "mean=",np.mean(c)

mean= 342.343333333


In [8]:
a = np.array([[1,2],[3,4]])
np.mean(a)

2.5

In [9]:
np.mean(a,axis=0)  # 纵向的

array([ 2.,  3.])

In [10]:
np.mean(a,axis=1)  # 横向的

array([ 1.5,  3.5])

In [11]:
#  找到最大值和最小值
h,l = np.loadtxt("/Users/fountain/Desktop/data.csv",delimiter=",",usecols=(4,5),unpack=True
                )
print "highest price=",np.max(h)
print "lowest price=",np.min(l)

highest price= 352.66
lowest price= 330.23


In [12]:
# ptp函数计算数组的取值范围
np.ptp(h)

13.650000000000034

In [13]:
np.ptp(l)

18.96999999999997

In [14]:
# usecols的参数为元组，它的元素个数为1个，为避免歧义，所以在后面多加了一个逗号表示确是一个元组，而不是其它 
c = np.loadtxt("/Users/fountain/Desktop/data.csv", delimiter=",", usecols=(6,),unpack=True)
print "中位数为",np.median(c)

中位数为 340.68


In [15]:
# 对数组进行排序   msort()函数
sorted_close = np.msort(c)
sorted_close

array([ 335.1 ,  336.1 ,  336.34,  345.02,  349.38,  352.12])

In [16]:
# 上面的数组为个数为偶数，所以中位数应该等于中间那两个数的平均值
N = len(c)
aver = (sorted_close[N/2] + sorted_close[(N-1)/2])/2
print "中位数为",aver

中位数为 340.68


In [17]:
# 计算方差：是指各个数据与所有数据算术平均数的离差平方和除以数据个数所得到的值
print "方差为",np.var(c)

方差为 46.6245888889


In [18]:
# 根据方差的定义即：
variance = np.mean((c-c.mean())**2)   # ndarray对象也有mean方法，所以数组c可以直接调用mean方法
print "方差为",variance

方差为 46.6245888889


In [19]:
#  注意样本方差和总体方差的区别。总体方差是用数据个数去除离差平方和（离差:指单项数值和平均值的差），而样本方
# 差则是用样本数据个数减1去除离差平方和，其中样本数据个数减1（即n-1）称为自由度。之所以有这样的差别，是为了
# 保证样本方差是一个无偏估计量。

In [20]:
import numpy as np
c = np.loadtxt("/Users/fountain/Desktop/data.csv",delimiter=",", usecols=(6,),unpack=True)
returns = np.diff(c)/c[:-1]
print returns
print "标准差=",np.std(returns)
logreturns = np.diff(np.log(c))   #  计算对数收益率
pos = np.where(returns > 0)   #  返回正数对应的索引
print pos  
annual_volatility = np.std(logreturns)/np.mean(logreturns)
annual_volatility = annual_volatility / np.sqrt(1./252.)  #  计算年波动率
print "年波动率=",annual_volatility
month_volatility = annual_volatility*np.sqrt(1./12.)
print "月波动率=",month_volatility

[-0.0029753   0.00370039  0.02580722  0.01263695  0.00784246]
标准差= 0.00967196267507
(array([1, 2, 3, 4]),)
年波动率= 16.2938120458
月波动率= 4.7036183854


In [21]:
!pip install tushare

In [22]:
!pip install beautifulsoup4

In [23]:
import tushare as ts
ts.get_hist_data('000001') # 一次性获取全部日k线数据

open   high  close    low      volume  price_change  p_change  \
date                                                                         
2018-01-08  13.25  13.29  12.96  12.86  2158620.75         -0.34     -2.56   
2018-01-05  13.21  13.35  13.30  13.15  1210312.75          0.05      0.38   
2018-01-04  13.32  13.37  13.25  13.13  1854509.50         -0.08     -0.60   
2018-01-03  13.73  13.86  13.33  13.20  2962498.25         -0.37     -2.70   
2018-01-02  13.35  13.93  13.70  13.32  2081592.50          0.40      3.01   
2017-12-29  13.21  13.43  13.30  13.10   982915.50          0.09      0.68   
2017-12-28  13.28  13.46  13.21  13.02  1553030.38         -0.08     -0.60   
2017-12-27  13.58  13.78  13.29  13.19  1366566.75         -0.37     -2.71   
2017-12-26  13.26  13.69  13.66  13.19  1123688.50          0.41      3.09   
2017-12-25  13.52  13.86  13.25  13.16  1585567.25         -0.27     -2.00   
2017-12-22  13.50  13.63  13.52  13.45   742900.94         -0.02     -0.15   
2017-12-21  13.18  13.68  13.54  13.16  1485203.50          0.28      2.11   
2017-12-20  13.20  13.31  13.26  13.13  1106245.00         -0.02     -0.15   
2017-12-19  12.79  13.32  13.28  12.74  2397943.00          0.53      4.16   
2017-12-18  12.73  12.91  12.75  12.64   805464.50          0.03      0.24   
2017-12-15  12.90  12.93  12.72  12.67  1099952.50         -0.28     -2.15   
2017-12-14  13.15  13.31  13.00  12.91  1001998.00         -0.13     -0.99   
2017-12-13  13.00  13.20  13.13  12.88  1289248.12          0.11      0.84   
2017-12-12  13.40  13.48  13.02  13.02  1743405.75         -0.48     -3.56   
2017-12-11  13.08  13.57  13.50  12.88  2261952.75          0.41      3.13   
2017-12-08  12.89  13.09  13.09  12.75  1351315.00          0.26      2.03   
2017-12-07  13.05  13.14  12.83  12.75  1181957.88         -0.25     -1.91   
2017-12-06  13.26  13.27  13.08  12.79  1619845.00         -0.22     -1.65   
2017-12-05  13.15  13.49  13.30  13.10  1723681.25          0.00      0.00   
2017-12-04  13.05  13.37  13.30  13.00  1454023.50          0.30      2.31   
2017-12-01  13.40  13.48  13.00  12.96  1784933.12         -0.38     -2.84   
2017-11-30  13.70  13.73  13.38  13.26  1379635.62         -0.44     -3.18   
2017-11-29  13.73  13.93  13.82  13.47  1564094.88          0.12      0.88   
2017-11-28  13.85  13.85  13.70  13.40  1766432.50         -0.23     -1.65   
2017-11-27  14.30  14.30  13.93  13.75  2064085.25         -0.63     -4.33   
...           ...    ...    ...    ...         ...           ...       ...   
2015-02-26  13.80  14.08  14.07  13.60  1025544.25          0.27      1.96   
2015-02-25  14.04  14.05  13.80  13.76   577392.31         -0.19     -1.36   
2015-02-24  14.07  15.39  15.38  14.01    66052.74          1.39      9.94   
2015-02-17  13.96  14.11  13.99  13.93   680491.56          0.07      0.50   
2015-02-16  13.95  14.01  13.92  13.73   721202.38         -0.03     -0.21   
2015-02-13  13.93  14.18  13.95  13.84   887743.12          0.09      0.65   
2015-02-12  13.75  13.90  13.86  13.62   608715.69          0.13      0.95   
2015-02-11  13.78  13.85  13.73  13.68   554349.50         -0.04     -0.29   
2015-02-10  13.49  13.82  13.77  13.42   724875.38          0.25      1.85   
2015-02-09  13.50  13.68  13.52  13.22   946586.25          0.01      0.07   
2015-02-06  13.69  13.95  13.51  13.40  1030408.56         -0.28     -2.03   
2015-02-05  14.30  14.43  13.79  13.76  1913729.12          0.08      0.58   
2015-02-04  14.00  14.04  13.71  13.70   807623.12         -0.24     -1.72   
2015-02-03  13.78  13.99  13.95  13.62   883349.12          0.32      2.35   
2015-02-02  13.60  13.80  13.63  13.55   860932.19         -0.30     -2.15   
2015-01-30  13.93  14.12  13.93  13.76   930116.69          0.03      0.22   
2015-01-29  13.82  14.01  13.90  13.75  1016753.31         -0.16     -1.14   
2015-01-28  13.87  14.30  14.06  13.80  1240877.50          0.07      0.50   
2015-01-27  14.35  14.37  13.99  13

In [24]:
# 设定起始时间
ts.get_hist_data('000001',start='2017-12-29',end='2018-01-08')

open   high  close    low      volume  price_change  p_change  \
date                                                                         
2018-01-08  13.25  13.29  12.96  12.86  2158620.75         -0.34     -2.56   
2018-01-05  13.21  13.35  13.30  13.15  1210312.75          0.05      0.38   
2018-01-04  13.32  13.37  13.25  13.13  1854509.50         -0.08     -0.60   
2018-01-03  13.73  13.86  13.33  13.20  2962498.25         -0.37     -2.70   
2018-01-02  13.35  13.93  13.70  13.32  2081592.50          0.40      3.01   
2017-12-29  13.21  13.43  13.30  13.10   982915.50          0.09      0.68   

               ma5    ma10    ma20       v_ma5      v_ma10      v_ma20  \
date                                                                     
2018-01-08  13.308  13.325  13.249  2053506.75  1687930.21  1540680.81   
2018-01-05  13.376  13.381  13.255  1818365.70  1546358.23  1500315.52   
2018-01-04  13.358  13.405  13.232  1886909.23  1573847.31  1498897.78   
2018-01-03  13.366  13.406  13.223  1789320.68  1499020.86  1487164.55   
2018-01-02  13.432  13.401  13.222  1421558.73  1442565.33  1425223.70   
2017-12-29  13.342  13.306  13.202  1322353.68  1314952.53  1393845.25   

            turnover  
date                  
2018-01-08      1.28  
2018-01-05      0.72  
2018-01-04      1.10  
2018-01-03      1.75  
2018-01-02      1.23  
2017-12-29      0.58

In [25]:
# 获取月k线数据
ts.get_hist_data('000001',ktype='W')

open   high  close    low       volume  price_change  p_change  \
date                                                                          
2018-01-08  13.25  13.29  12.96  12.86         0.00         -0.34     -2.56   
2018-01-05  13.35  13.93  13.30  13.13         0.00          0.00      0.00   
2017-12-29  13.52  13.86  13.30  13.02         0.00         -0.22     -1.63   
2017-12-22  12.73  13.68  13.52  12.64         0.00          0.80      6.29   
2017-12-15  13.08  13.57  12.72  12.67         0.00         -0.37     -2.83   
2017-12-08  13.05  13.49  13.09  12.75         0.00          0.09      0.69   
2017-12-01  14.30  14.30  13.00  12.96         0.00         -1.56    -10.71   
2017-11-24  13.13  15.24  14.56  13.05         0.00          1.38     10.47   
2017-11-17  12.35  13.46  13.18  12.35         0.00          0.88      7.15   
2017-11-10  11.42  12.59  12.30  11.09   7769891.50          0.91      7.99   
2017-11-03  11.55  11.73  11.39  11.26   3946008.00         -0.17     -1.47   
2017-10-27  11.39  11.56  11.56  11.12   4400993.00          0.08      0.70   
2017-10-20  11.36  11.72  11.48  11.29   3598561.00          0.12      1.06   
2017-10-13  11.57  11.64  11.36  11.25   4046671.25          0.25      2.25   
2017-09-29  11.44  11.45  11.11  10.82   3426540.00         -0.33     -2.88   
2017-09-22  11.25  11.52  11.44  11.05   3445316.00          0.15      1.33   
2017-09-15  11.54  11.69  11.29  11.15   3743076.25         -0.20     -1.74   
2017-09-08  11.18  11.94  11.49  11.17   4526929.50          0.28      2.50   
2017-09-01  11.10  11.74  11.21  11.10   6170360.00          0.10      0.90   
2017-08-25  10.43  11.17  11.11  10.37   4482177.00          0.67      6.42   
2017-08-18  10.13  10.60  10.44  10.04   4159795.50          0.42      4.19   
2017-08-11  11.06  11.17  10.02   9.99   5993057.00         -1.15    -10.29   
2017-08-04  10.80  11.34  11.17  10.45   8011814.50          0.43      4.00   
2017-07-28  10.82  11.27  10.74  10.53   7358531.00         -0.15     -1.38   
2017-07-21  10.95  11.33  10.89  10.62  10593990.00         -0.01     -0.09   
2017-07-14   9.45  10.94  10.90   9.44  12888852.00          1.43     15.10   
2017-07-07   9.40   9.48   9.47   9.27   2943713.50          0.08      0.85   
2017-06-30   9.26   9.49   9.39   9.26   3414020.50          0.14      1.51   
2017-06-23   9.03   9.40   9.25   9.02   3311215.00          0.23      2.55   
2017-06-16   9.15   9.19   9.02   9.01   1952246.25         -0.13     -1.42   
...           ...    ...    ...    ...          ...           ...       ...   
1991-10-25  24.00  24.40  24.00  23.25     17632.00         -0.15     -0.62   
1991-10-18  24.40  25.10  24.15  22.10     23067.00          0.15      0.62   
1991-10-11  16.00  27.85  24.00  16.00     31748.00          8.40     53.85   
1991-10-04  14.60  16.10  15.60  14.60      5740.00          1.10      7.59   
1991-09-27  14.05  14.60  14.50  14.05      7443.00          0.40      2.84   
1991-09-20  14.30  14.35  14.10  14.00     13684.00         -0.40     -2.76   
1991-09-13  13.70  14.50  14.50  13.70     26109.00          0.80      5.84   
1991-09-06  15.00  15.00  13.70  13.50     14901.00         -1.35     -8.97   
1991-08-30  15.60  15.60  15.05  15.00     11843.00          0.05      0.33   
1991-08-23  16.00  16.30  15.00  14.30     15722.00        -14.24    -48.70   
1991-08-16  29.24  29.24  29.24  29.24         0.00          0.00      0.00   
1991-08-09  29.24  29.24  29.24  29.24         0.00          0.00      0.00   
1991-08-02  29.84  29.84  29.24  29.24        23.00         -0.90     -2.99   
1991-07-26  30.89  30.89  30.14  30.14         5.00         -0.91     -2.93   
1991-07-19  31.69  31.69  31.05  31.05         5.00         -1.12     -3.48   
1991-07-12  32.65  32.65  32.17  32.17        16.00         -0.80     -2.43   
1991-07-05  33.65  33.65  32.97  32.97        17.00         -1.02     -3.00   
1991-06-28  34.67  34.67  33.99  33.99        47.00         -1.

In [26]:
# 获取30分钟k线数据
ts.get_hist_data('000001',ktype='30')

open   high  close    low     volume  price_change  \
date                                                                       
2018-01-08 15:00:00  12.91  12.97  12.96  12.90   140075.0          0.05   
2018-01-08 14:30:00  12.95  12.97  12.91  12.87   262166.0         -0.04   
2018-01-08 14:00:00  12.90  13.02  12.95  12.87   229268.0          0.05   
2018-01-08 13:30:00  12.95  12.95  12.90  12.86   367396.0         -0.05   
2018-01-08 11:30:00  13.03  13.06  12.95  12.95   269650.0         -0.08   
2018-01-08 11:00:00  13.04  13.07  13.03  12.98   280023.0         -0.01   
2018-01-08 10:30:00  13.15  13.17  13.04  13.03   317936.0         -0.11   
2018-01-08 10:00:00  13.24  13.26  13.15  13.13   271852.0         -0.09   
2018-01-05 15:00:00  13.28  13.30  13.30  13.24   158227.0          0.02   
2018-01-05 14:30:00  13.25  13.29  13.28  13.23    84401.6          0.03   
2018-01-05 14:00:00  13.32  13.33  13.25  13.23   127332.0         -0.07   
2018-01-05 13:30:00  13.22  13.34  13.31  13.20   248429.0          0.09   
2018-01-05 11:30:00  13.20  13.22  13.21  13.15   129758.0          0.01   
2018-01-05 11:00:00  13.22  13.23  13.20  13.18   118619.0         -0.02   
2018-01-05 10:30:00  13.27  13.27  13.22  13.18   152286.0         -0.05   
2018-01-05 10:00:00  13.21  13.27  13.27  13.17   180744.0          0.06   
2018-01-04 15:00:00  13.27  13.27  13.25  13.21   149998.0         -0.02   
2018-01-04 14:30:00  13.16  13.28  13.27  13.15   153118.0          0.11   
2018-01-04 14:00:00  13.19  13.25  13.16  13.15   363591.0         -0.03   
2018-01-04 13:30:00  13.33  13.35  13.19  13.18   227198.0         -0.14   
2018-01-04 11:30:00  13.26  13.37  13.33  13.25   210071.0          0.07   
2018-01-04 11:00:00  13.28  13.29  13.26  13.22   144571.0         -0.02   
2018-01-04 10:30:00  13.21  13.31  13.29  13.20   165398.0          0.08   
2018-01-04 10:00:00  13.29  13.33  13.21  13.14   422866.0         -0.08   
2018-01-03 15:00:00  13.50  13.50  13.33  13.21   959800.0         -0.17   
2018-01-03 14:30:00  13.47  13.54  13.50  13.43   338046.0          0.03   
2018-01-03 14:00:00  13.62  13.63  13.46  13.46   384749.0         -0.16   
2018-01-03 13:30:00  13.71  13.76  13.62  13.56   267596.0         -0.09   
2018-01-03 11:30:00  13.71  13.75  13.71  13.62   243581.0          0.00   
2018-01-03 11:00:00  13.77  13.85  13.72  13.69   264562.0         -0.05   
...                    ...    ...    ...    ...        ...           ...   
2017-11-10 15:00:00  12.29  12.33  12.30  12.23   335453.0          0.01   
2017-11-10 14:30:00  12.39  12.40  12.28  12.26   201028.0         -0.11   
2017-11-10 14:00:00  12.49  12.55  12.39  12.38   165486.0         -0.10   
2017-11-10 13:30:00  12.42  12.55  12.48  12.41   193144.0          0.06   
2017-11-10 11:30:00  12.32  12.44  12.43  12.28   146213.0          0.11   
2017-11-10 11:00:00  12.19  12.34  12.31  12.18   133756.0          0.12   
2017-11-10 10:30:00  12.27  12.28  12.20  12.15   220790.0         -0.07   
2017-11-10 10:00:00  12.35  12.42  12.28  12.20   332827.0         -0.07   
2017-11-09 15:00:00  12.26  12.38  12.32  12.26   172918.0          0.06   
2017-11-09 14:30:00  12.34  12.34  12.27  12.21   199430.0         -0.07   
2017-11-09 14:00:00  12.41  12.46  12.35  12.34   121715.0         -0.06   
2017-11-09 13:30:00  12.50  12.51  12.40  12.38   160161.0         -0.10   
2017-11-09 11:30:00  12.46  12.53  12.50  12.45   169718.0          0.04   
2017-11-09 11:00:00  12.42  12.50  12.47  12.39   179936.0          0.05   
2017-11-09 10:30:00  12.48  12.53  12.41  12.35   356456.0         -0.07   
2017-11-09 10:00:00  12.19  12.56  12.49  12.15   892698.0          0.30   
2017-11-08 15:00:00  11.96  12.12  12.09  11.96   223332.0          0.13   
2017-11-08 14:30:00  12.12  12.12  11.99  11.94  1105540.0         -0.13   
2017-11-08 14:00:00  12.35  12.35  12.12  12.07   636891.0         -0.23   
2017-11-08 13:30:00  12.42  12.46  12.33  12.21   272806.0         -0.

In [28]:
import time

# 获取个股首个上市日期
df = ts.get_stock_basics()
date = df.loc['000001']['timeToMarket']
print "平安银行上市日期为",date

平安银行上市日期为 19910403


In [29]:
dateStr = str(date) #  将int类型的date转换为字符串

# strptime(string,format) 将时间字符串指定的格式化符转换成struct_time类型
da = time.strptime(dateStr,'%Y%m%d')  
print  da

# strftime(format,[struct_time]) 返回以可读字符串表示的当地时间。struct_time可选
print "平安银行上市日期为",time.strftime('%Y-%m-%d',da)

time.struct_time(tm_year=1991, tm_mon=4, tm_mday=3, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=2, tm_yday=93, tm_isdst=-1)
平安银行上市日期为 1991-04-03


In [30]:
time.strftime("%Y-%m-%d")

'2018-01-08'

In [35]:
ts.realtime_boxoffice()   # 获取实时电影票房数据

BoxOffice Irank     MovieName boxPer movieDay sumBoxOffice  \
0    6405.17     1      前任3：再见前任  70.11       11    136432.01   
1    1062.15     2  星球大战：最后的绝地武士  11.63        4     19674.76   
2     641.16     3            芳华   7.02       25    136419.13   
3     316.54     4     二代妖精之今生有幸   3.46       11     26980.58   
4     179.66     5           妖铃铃   1.97       11     35335.23   
5     154.48     6           妖猫传   1.69       18     51884.28   
6     133.02     7         解忧杂货店   1.46       11     21653.34   
7     117.90     8         寻梦环游记   1.29       46    119638.17   
8      26.19     9      心理罪之城市之光   0.29       18     22193.06   
9      22.92    10          机器之血   0.25       18     30381.15   
10     76.42    11            其它   1.00        0         0.00   

                   time  
0   2018-01-08 18:53:39  
1   2018-01-08 18:53:39  
2   2018-01-08 18:53:39  
3   2018-01-08 18:53:39  
4   2018-01-08 18:53:39  
5   2018-01-08 18:53:39  
6   2018-01-08 18:53:39  
7   2018-01-08 18:53:39  
8   2018-01-08 18:53:39  
9   2018-01-08 18:53:39  
10  2018-01-08 18:53:39

In [37]:
ts.day_boxoffice()  # 取上一日的数据

AvgPrice AvpPeoPle BoxOffice BoxOffice_Up IRank MovieDay     MovieName  \
0       35        12      4813          -75     1       11      前任3：再见前任   
1       37         4       820          -83     2        4  星球大战：最后的绝地武士   
2       34         6       497          -75     3       25            芳华   
3       35         5       235          -76     4       11     二代妖精之今生有幸   
4       35         3       136          -73     5       11           妖铃铃   
5       36         6       123          -72     6       18           妖猫传   
6       33         4       106          -72     7       11         解忧杂货店   
7       33         5        95          -87     8       46         寻梦环游记   
8      246       371        27           80     9       -3          卧底巨星   
9       35         4        22          -66    10       18      心理罪之城市之光   

  SumBoxOffice WomIndex  
0       134798           
1        19422           
2       136271           
3        26896           
4        35287           
5        51852           
6        21624           
7       119615           
8           55           
9        22188

In [39]:
ts.day_boxoffice('2018-01-07') #取指定日期的数据

AvgPrice AvpPeoPle BoxOffice BoxOffice_Up IRank MovieDay     MovieName  \
0       35        12      4813          -75     1       11      前任3：再见前任   
1       37         4       820          -83     2        4  星球大战：最后的绝地武士   
2       34         6       497          -75     3       25            芳华   
3       35         5       235          -76     4       11     二代妖精之今生有幸   
4       35         3       136          -73     5       11           妖铃铃   
5       36         6       123          -72     6       18           妖猫传   
6       33         4       106          -72     7       11         解忧杂货店   
7       33         5        95          -87     8       46         寻梦环游记   
8      246       371        27           80     9       -3          卧底巨星   
9       35         4        22          -66    10       18      心理罪之城市之光   

  SumBoxOffice WomIndex  
0       134798           
1        19422           
2       136271           
3        26896           
4        35287           
5        51852           
6        21624           
7       119615           
8           55           
9        22188

In [41]:
df = ts.month_boxoffice() #取上一月票房数据
df

Irank  MovieName WomIndex avgboxoffice avgshowcount box_pro boxoffice days  \
0      1         芳华     8.18           34           28    23.3    118691   17   
1      2      寻梦环游记     9.29           34           18    18.5     94309   31   
2      3        妖猫传     7.52           35           26     9.2     46859   10   
3      4       奇门遁甲     7.07           34           14     5.9     29892   18   
4      5   前任3：再见前任     7.96           35           48     5.8     29500    3   
5      6       机器之血     7.58           34           19     5.7     29174   10   
6      7        妖铃铃     6.87           34           34     4.9     25145    3   
7      8   心理罪之城市之光     7.82           32           18     4.2     21385   10   
8      9      帕丁顿熊2     8.38           29           11     3.9     19834   24   
9     10  二代妖精之今生有幸     7.74           34           28     3.3     16955    3   
10   999         其他                    32            9    15.1     76672        

   releaseTime  
0   2017-12-15  
1   2017-11-24  
2   2017-12-22  
3   2017-12-14  
4   2017-12-29  
5   2017-12-22  
6   2017-12-29  
7   2017-12-22  
8   2017-12-08  
9   2017-12-29  
10

In [45]:
df = ts.month_boxoffice('2017-10') #取2015年10月的数据
df

Irank  MovieName WomIndex avgboxoffice avgshowcount box_pro boxoffice days  \
0      1      羞羞的铁拳     7.92           34           26    39.1    200615   31   
1      2         追龙     7.88           33           20    10.3     52842   31   
2      3       英伦对决     7.51           38           18     9.0     45907   31   
3      4  王牌特工2：黄金圈     7.60           35           15     8.5     43520   12   
4      5      缝纫机乐队     7.80           33           17     7.5     38673   31   
5      6       全球风暴     6.45           35           18     5.6     28484    5   
6      7       天才枪手     8.39           30           13     5.1     25961   19   
7      8        空天猎     7.33           36           18     5.0     25802   31   
8      9       十八洞村     8.35           38           11     1.6      8236   19   
9     10   银翼杀手2049     8.08           35            8     1.2      6044    5   
10   999         其他                    32            8     7.2     36805        

   releaseTime  
0   2017-09-30  
1   2017-09-30  
2   2017-09-30  
3   2017-10-20  
4   2017-09-29  
5   2017-10-27  
6   2017-10-13  
7   2017-09-29  
8   2017-10-13  
9   2017-10-27  
10

In [51]:
ts.month_boxoffice('2017-12')

Irank  MovieName WomIndex avgboxoffice avgshowcount box_pro boxoffice days  \
0      1         芳华     8.18           34           28    23.3    118691   17   
1      2      寻梦环游记     9.29           34           18    18.5     94309   31   
2      3        妖猫传     7.52           35           26     9.2     46859   10   
3      4       奇门遁甲     7.07           34           14     5.9     29892   18   
4      5   前任3：再见前任     7.96           35           48     5.8     29500    3   
5      6       机器之血     7.58           34           19     5.7     29174   10   
6      7        妖铃铃     6.87           34           34     4.9     25145    3   
7      8   心理罪之城市之光     7.82           32           18     4.2     21385   10   
8      9      帕丁顿熊2     8.38           29           11     3.9     19834   24   
9     10  二代妖精之今生有幸     7.74           34           28     3.3     16955    3   
10   999         其他                    32            9    15.1     76672        

   releaseTime  
0   2017-12-15  
1   2017-11-24  
2   2017-12-22  
3   2017-12-14  
4   2017-12-29  
5   2017-12-22  
6   2017-12-29  
7   2017-12-22  
8   2017-12-08  
9   2017-12-29  
10

In [54]:
# 获取被暂停上市的股票列表，数据从上交所获取，
# 目前只有在上海证券交易所交易被终止的股票。
ts.get_suspended() 

code   name       oDate tDate
0  600432  *ST吉恩  2003-09-05     -
1  600806  *ST昆机  1994-01-03     -

In [65]:
ts.get_stock_basics()

name industry area      pe  outstanding  totals  totalAssets  \
code                                                                    
002610   爱康科技     电气设备   江苏   59.40        42.79   44.91   1815202.38   
002587   奥拓电子      元器件   深圳   40.83         3.72    6.11    155489.67   
600353   旭光股份      元器件   四川   91.21         5.44    5.44    166766.48   
600246   万通地产     区域地产   北京   68.71        12.17   20.54   1415504.75   
002447   壹桥股份      互联网   辽宁  122.63         9.64   14.27    324293.28   
002591   恒大高新     化工原料   江西    0.00         1.76    3.07    144139.25   
002369   卓翼科技     通信设备   深圳  418.58         4.20    5.81    339044.44   
600571    信雅达     软件服务   浙江  151.54         4.24    4.40    169000.06   
603386   广东骏亚      元器件   广东   55.58         0.51    2.02    121684.05   
300085    银之杰     软件服务   深圳  290.19         3.92    7.07    224731.95   
000021    深科技     电脑设备   深圳   26.61        14.69   14.71   1679054.25   
300462   华铭智能     专用机械   上海   96.50         0.56    1.38     81888.28   
002289   宇顺电子      元器件   深圳    0.00         2.60    2.80     79391.06   
300491   通合科技     电气设备   河北    0.00         0.51    1.46     56326.61   
603367   辰欣药业     化学制药   山东   36.97         1.00    4.53    469326.06   
300684   中石科技     化工原料   北京   65.54         0.22    0.87     61019.13   
000070   特发信息     通信设备   深圳   27.97         5.42    6.27    579230.81   
600209   罗顿发展      综合类   海南    0.00         4.26    4.39     86705.93   
300466   赛摩电气     电器仪表   江苏  220.45         1.78    5.53    175914.05   
600903   贵州燃气     供气供热   贵州  144.69         1.22    8.13    751383.75   
300662   科锐国际      综合类   北京   62.14         0.45    1.80     88471.28   
300736   百华悦邦     通信设备   北京   41.60         0.14    0.54     26685.90   
002907   华森制药     化学制药   重庆  114.16         0.40    4.00     70735.78   
600446   金证股份     软件服务   深圳  392.66         8.01    8.53    359036.94   
300682   朗新科技     软件服务   江苏    0.00         0.45    4.17    125838.76   
002230   科大讯飞     软件服务   安徽  410.20        11.83   13.89   1222074.13   
300663   科蓝软件     软件服务   北京    0.00         0.33    1.34    100504.81   
603106   恒银金融     电脑设备   天津   46.40         0.70    2.80    212309.42   
603912    佳力图     专用机械   江苏   59.90         0.37    1.48     60002.80   
002657   中科金财     软件服务   北京   58.27         2.76    3.38    426394.09   
...       ...      ...  ...     ...          ...     ...          ...   
603588   高能环境     环境保护   北京   45.47         6.50    6.62    545736.44   
000786   北新建材     其他建材   北京   20.15        14.14   17.89   1640711.75   
000885   同力水泥       水泥   河南   10.68         4.27    4.96    790873.75   
002809   红墙股份     化工原料   广东   50.82         0.60    1.25    118162.27   
600715   文投控股     影视音像   辽宁   70.18         4.49   18.55   1005230.38   
000040   东旭蓝天     新型电力   深圳   40.13        10.60   13.37   2480558.00   
600917   重庆燃气     供气供热   重庆   43.27        15.56   15.56    840338.88   
300621   维业股份     装修装饰   深圳   40.31         0.34    1.39    186181.06   
600720    祁连山       水泥   甘肃   11.18         7.76    7.76   1036219.19   
002110   三钢闽光       普钢   福建    9.51         9.91   13.74   1548558.13   
601636   旗滨集团       玻璃   湖南   17.22        25.13   26.80   1295578.63   
000789    万年青       水泥   江西   25.91         6.13    6.13    845172.88   
600585   海螺水泥       水泥   安徽   12.66        40.00   52.99  11652647.00   
000672   上峰水泥       水泥   甘肃   15.47         8.14    8.14    624103.44   
300624   万兴科技     软件服务   西藏    0.00         0.00    0.00     27383.02   
002925   盈趣科技      元器件   福建    0.00         0.00    0.00    230804.05   
000950  *ST建峰     农药化肥   重庆    0.00         5.99   17.28   1562395.13   
000629  *ST钒钛       普钢   四川    0.00        47.67   85.90    999802.19   
000511  *ST烯碳     矿物制品   辽宁    0.00        11.55   11.55    346274.91   
603895   天永智能     专用机械   上海    0.00         0.00    0.00     62081.06   
603506   南都物业     区域地产   浙江    0.00         0.00    0.00     72642.00   
603356   华菱精工     机械基件   安徽    0.00         0.00    0.00     52746.

In [6]:
import numpy as np
arr = np.array([1,2,3], dtype=np.int32)
arr.dtype

dtype('int32')

In [11]:
arr = np.array([2.4, 3.9, 4.0,5.2,-2.9])
arr.dtype

dtype('float64')

In [15]:
float_arr = arr.astype(np.int32)
float_arr

array([ 2,  3,  4,  5, -2], dtype=int32)

In [26]:
# 如果字符串数组表示的全是数字，也可以用astype将其转换为数值形式
numeric_string = np.array(['2.3686', '-9.3', '32', '2', '233', '1'], dtype=np.string_)
numeric_string.dtype  # S6表示其中的字符串最大为6个字节

dtype('S6')

In [27]:
num_arr = numeric_string.astype(np.float64)
num_arr

array([   2.3686,   -9.3   ,   32.    ,    2.    ,  233.    ,    1.    ])

In [37]:
# 基本的索引和切片
arr = np.arange(10)
print arr
print arr[5:8]
arr[5:8] = 12
arr

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [33]:
arr_slice = arr[5:8]
arr_slice[1] = 123
arr

array([  0,   1,   2,   3,   4,  12, 123,  12,   8,   9])

In [34]:
arr_slice[:] = 6
arr

array([0, 1, 2, 3, 4, 6, 6, 6, 8, 9])

In [35]:
arr_slice = arr[5:8].copy()
arr

array([0, 1, 2, 3, 4, 6, 6, 6, 8, 9])

In [38]:
arr_slice[2] = 23333
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [40]:
# 二维数组
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d[2]

array([7, 8, 9])

In [42]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
print arr2d
arr2d[:2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
arr2d[:,1:]  # 获取2，3  5，6  8，9

array([[2, 3],
       [5, 6],
       [8, 9]])

In [65]:
arr2d[2,1:]   #获取8，9

array([8, 9])

In [84]:
arr2d[:,2:]      #获取3，6，9

array([[3],
       [6],
       [9]])

In [78]:
arr2d[:2,1:]   # 获取2，3    5，6

array([[2, 3],
       [5, 6]])

In [74]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [82]:
!cat eye.txt

1.000000000000000000e+00 0.000000000000000000e+00
0.000000000000000000e+00 1.000000000000000000e+00


In [7]:
import numpy as np

# 对前6项数据进行排序
arr = np.array([1,6,3,-2,0,5,8,2])

# arr[:6].argsort()这一步得到的结果是排好序的数据的索引

arr = arr[arr[:6].argsort()]
arr


array([-2,  0,  1,  3,  5,  6])