In [5]:
# np.random.random()
import numpy as np
x = np.random.random(5)
print x
print x+1

[ 0.38705818  0.22546475  0.81028904  0.04723186  0.17194541]
[ 1.38705818  1.22546475  1.81028904  1.04723186  1.17194541]


In [6]:
# Numpy的ndarray类似于Python的列表，但是ndarray要求存储在数组中的元素类型
# 必须一致。而同一个python列表中可以存储不同类型的元素。

In [48]:
# np.random.rand(d0,d1,..,dn) 返回值为指定维度的array，数据为[0,1)之间
np.random.rand(2,4)

array([[ 0.38344152,  0.79172504,  0.52889492,  0.56804456],
       [ 0.92559664,  0.07103606,  0.0871293 ,  0.0202184 ]])

In [49]:
np.random.rand() # rand函数根据给定维度生成[0,1)之间的数据，包含0，不包含1

0.832619845547938

In [50]:
np.random.rand(3,2,2)

array([[[ 0.77815675,  0.87001215],
        [ 0.97861834,  0.79915856]],

       [[ 0.46147936,  0.78052918],
        [ 0.11827443,  0.63992102]],

       [[ 0.14335329,  0.94466892],
        [ 0.52184832,  0.41466194]]])

In [55]:
# np.random.randn()返回一个或一组样本，具有标准正态分布。
np.random.randn()

0.04575851730144607

In [58]:
np.random.randn(2,3)

array([[-1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682]])

In [60]:
np.random.randn(2,3,2)

array([[[ 0.3869025 , -0.51080514],
        [-1.18063218, -0.02818223],
        [ 0.42833187,  0.06651722]],

       [[ 0.3024719 , -0.63432209],
        [-0.36274117, -0.67246045],
        [-0.35955316, -0.81314628]]])

In [69]:
# np.random.randint()
np.random.randint(2,size=10)

array([0, 1, 0, 1, 0, 0, 1, 1, 0, 0])

In [71]:
# high没有指明时，默认生成随机数的范围为[0,low)
np.random.randint(5,size=(3,2))

array([[4, 3],
       [4, 0],
       [4, 3]])

In [73]:
#  指明了参数low，high,size
np.random.randint(-2,6,size=(3,4))

array([[ 3,  4, -1, -2],
       [ 2, -1,  4,  3],
       [ 3,  1, -1, -2]])

In [83]:
# np.random.choice()
np.random.choice(5,3)
# 它等同于 np.random.randint(0,5,3)

array([3, 0, 4])

In [96]:
# 当replace为False时，生成的随机数不会有重复的数据
np.random.choice(5,3,replace=False)

array([2, 3, 0])

In [107]:
aa_milne_arr = ['pooh', 'rabbit', 'piglet', 'Christopher']
# p为数组中的数据出现的概率
np.random.choice(aa_milne_arr, 8, p=[0.5, 0.1, 0.1, 0.3])

array(['Christopher', 'pooh', 'rabbit', 'pooh', 'Christopher', 'pooh',
       'rabbit', 'pooh'],
      dtype='|S11')

In [108]:
#  np.random.seed()的作用是：使得随机数据可预测
# 当我们设置相同的seed，每次生成的随机数是相同的。不设置的话，则每次都不同
np.random.seed(0)
np.random.rand(9)

array([ 0.5488135 ,  0.71518937,  0.60276338,  0.54488318,  0.4236548 ,
        0.64589411,  0.43758721,  0.891773  ,  0.96366276])

In [112]:
# 生成[0.0, 1.0)之间的浮点数,参数为int 或者int构成的元组；或可选
# numpy.random.random(size=None)
# numpy.random.ranf(size=None)
# numpy.random.sample(size=None)
np.random.random_sample(6)

array([ 0.79915856,  0.46147936,  0.78052918,  0.11827443,  0.63992102,
        0.14335329])

In [114]:
np.random.random_sample()

0.5218483217500717

In [120]:
np.random.random_sample((3,2))

array([[ 0.10204481,  0.20887676],
       [ 0.16130952,  0.65310833],
       [ 0.2532916 ,  0.46631077]])

In [123]:
# np.random.normal()得到一个正态(高斯)分布的样本数组
samples = np.random.normal(size=(4,4))
samples

array([[ 0.92525075, -0.90478616,  1.84369153,  1.52550724],
       [-1.44553558,  0.37716061, -0.07055723,  0.60415971],
       [ 0.472149  ,  0.81991729,  0.90751962, -0.58582287],
       [ 0.93755884, -0.25460809,  0.97359871,  0.20728277]])

In [125]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0,1) for _ in xrange(N)]

1 loop, best of 3: 971 ms per loop


In [127]:
%timeit np.random.normal(size=N)
# 从两个结果来看，如果要产生大量样本值，numpy.random比python内置的
# random模块快了不止一个数量级

10 loops, best of 3: 43.2 ms per loop


In [134]:
import random
position = 0
walk = [position]
steps = 1000
for i in xrange(steps):
    step = 1 if random.randint(0,1) else -1
    position += step
    walk.append(position)
print walk
print len(walk)

[0, 1, 2, 1, 2, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 5, 4, 5, 4, 5, 6, 5, 6, 7, 6, 7, 6, 5, 6, 5, 6, 7, 8, 9, 10, 11, 12, 13, 12, 13, 14, 15, 16, 17, 16, 15, 16, 15, 14, 13, 12, 11, 10, 9, 8, 9, 10, 11, 10, 11, 12, 11, 12, 11, 12, 13, 12, 13, 14, 15, 16, 15, 16, 15, 14, 15, 14, 13, 14, 13, 12, 13, 14, 13, 14, 13, 12, 13, 12, 11, 12, 13, 14, 15, 14, 15, 14, 15, 16, 17, 18, 17, 16, 17, 18, 19, 20, 19, 20, 21, 22, 23, 24, 25, 24, 23, 24, 25, 26, 25, 24, 23, 24, 25, 24, 23, 24, 25, 24, 25, 24, 25, 24, 25, 24, 23, 24, 23, 24, 23, 22, 23, 24, 23, 24, 25, 26, 25, 26, 25, 26, 27, 26, 27, 26, 25, 24, 23, 24, 23, 24, 23, 24, 25, 26, 25, 24, 25, 24, 23, 22, 21, 22, 23, 24, 25, 26, 27, 26, 25, 24, 23, 24, 25, 26, 25, 24, 25, 24, 25, 26, 25, 24, 25, 26, 25, 24, 23, 24, 25, 24, 23, 24, 25, 26, 27, 28, 29, 30, 29, 28, 27, 28, 29, 30, 31, 30, 29, 28, 29, 28, 27, 26, 27, 26, 25, 24, 23, 22, 21, 22, 23, 22, 21, 22, 21, 22, 23, 22, 21, 22, 21, 22, 23, 24, 25, 26, 27, 26, 25, 26, 27, 26, 25, 26, 25, 24, 23, 22, 

In [140]:
nsteps = 1000
draws = np.random.randint(0,2,size=nsteps)
steps = np.where(draws>0,1,-1)
walk = steps.cumsum()
print walk
print walk.min()
print walk.max()

[ -1  -2  -3  -4  -5  -6  -5  -6  -5  -4  -5  -6  -5  -4  -3  -2  -3  -2
  -1  -2  -1   0   1   0   1   0   1   2   1   0   1   2   1   2   3   2
   1   0  -1  -2  -1   0   1   2   1   0  -1  -2  -3  -4  -5  -4  -5  -6
  -7  -6  -5  -6  -5  -6  -5  -4  -3  -2  -3  -2  -1  -2  -1   0   1   2
   3   4   5   6   7   6   5   6   5   6   5   4   5   4   3   2   1   2
   3   2   1   2   1   2   1   0  -1   0   1   0  -1   0  -1  -2  -3  -2
  -1   0   1   0  -1  -2  -1   0  -1  -2  -1  -2  -1  -2  -1   0   1   2
   1   2   1   0  -1   0  -1   0   1   2   1   0   1   0   1   0   1   0
  -1  -2  -1   0  -1  -2  -3  -4  -5  -4  -3  -2  -3  -4  -5  -6  -7  -8
  -7  -8  -9  -8  -9 -10  -9  -8  -7  -8  -7  -6  -5  -6  -5  -6  -7  -8
  -9  -8  -9  -8  -9 -10  -9  -8  -9 -10  -9 -10 -11 -10  -9 -10 -11 -10
 -11 -10 -11 -12 -11 -12 -11 -12 -13 -12 -11 -10  -9  -8  -7  -8  -7  -6
  -7  -8  -9  -8  -7  -8  -9 -10 -11 -10  -9 -10 -11 -10 -11 -12 -13 -12
 -11 -10 -11 -10 -11 -12 -13 -14 -15 -14 -15 -16 -1